version: '3'

services:
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=fingernft
    ports:
      - "3306:3306"
    volumes:
      - "./fingernft.sql:/docker-entrypoint-initdb.d/1.sql"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    platform: linux/x86_64
